'use client';

import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'en' | 'te' | 'ta' | 'hi';

interface Dictionary {
  [key: string]: string;
}

const translations: Record<Language, Dictionary> = {
  en: {
    helphub: 'HelpHub',
    hero_title_1: 'Report, Resolve,',
    hero_title_2: 'Rebuild.',
    hero_subtitle: 'The modern way to report civic and welfare issues in your neighborhood. From potholes to public safety, let your voice be heard—even anonymously.',
    get_started: 'Get Started',
    subtitle: 'Civic and Welfare Reporting System',
    select_language: 'Select Language',
    user_access: 'User Login / Register',
    admin_access: 'Admin',
    volunteer_access: 'Volunteer Login / Register',
    anonymous_report: 'Report Anonymously',
    login: 'Login',
    register: 'Register',
    report_issue: 'Report an Issue',
    my_reports: 'My Reports',
    emergency_call: 'Emergency Call',
    instructions: 'Instructions / Help',
    name: 'Name',
    phone: 'Phone Number',
    age: 'Age',
    city: 'City',
    email: 'Email',
    password: 'Password',
    confirm_password: 'Confirm Password',
    submit: 'Submit',
    back: 'Back',
    assistant_title: 'HelpHub Assistant',
    assistant_subtitle: 'Chat with our AI bot to get help with common issues.',
    assistant_greeting: "Hello! I am HelpHub's automated assistant. You can ask me questions like 'I can't upload image', 'location not working', or 'how to report issue'. How can I help you today?",
    chat_placeholder: 'Type your question here...',
    search_location: '📍 Search Location',
    search_placeholder: 'Type city or area (e.g. Tirupati, Andhra Pradesh)',
    search_button: 'Search',
    searching: 'Searching...',
    search_help_text: 'Please search for a location to view the map and verify your coordinates before submitting.',
    confirmed: '📍 Confirmed',
    re_enter_location: '✏️ Re-enter location',
    confirm_location_button: '✅ Confirm This Location',
    category: '🏷️ Category',
    category_placeholder: 'e.g. Animal Issue, Road, Waste...',
    upload_photo: '📸 Upload Photo',
    voice_input: '🎤 Voice Input',
    start_recording: 'Start Recording',
    stop_recording: 'Stop Recording',
    recording_status: 'Recording...',
    manual_input: '⌨️ Manual Text Input',
    manual_input_placeholder: 'Describe the issue in detail...',
    contact_info_label: 'Leave Contact Info (Optional)',
    contact_info_help: 'If there are no nearby volunteers, an admin can contact you regarding this issue.',
    contact_info_placeholder: 'Email or Phone Number',
    user_dashboard: 'User Dashboard',
    account_id: 'Account ID',
    saving: 'Saving...',
    confirmed_coords: 'Coordinates',
    smart_suggestions: '✨ Smart Suggestions (Click to select)',
    selected_issue: 'Selected Issue',
    converted_text: 'Converted Text',
    strict_location_warning: 'Please strictly confirm your location above before submitting a report.',
    logout: 'Logout',
    my_profile: 'My Profile',
    home: 'Home',
    login_register: 'Login / Register',
    help_chat: 'Help / Chat',
    anonymous_report_nav: 'Anonymous Report',
    assigned_issues: 'Assigned Issues',
    nearby_unassigned: 'Nearby Unassigned',
    requested_assignments: 'Requested Assignments',
    issue_management: 'Issue Management',
    volunteers: 'Volunteers',
    assignment_requests: 'Assignment Requests',
    emergency_call_nav: '🚨 Emergency Call',
    report_an_issue_nav: 'Report an Issue',
    loading_dashboard: 'Loading Dashboard...',
    selected_issue_label: 'Selected Issue',
    date: 'Date',
    admin_reply: 'Admin Reply',
    saving_changes: 'Saving Changes...',
    save_profile_details: 'Save Profile Details',
    recovery_codes_title: 'Account Recovery Codes',
    hide: 'Hide',
    reveal: 'Reveal',
    recovery_codes_help: 'Save these 4 unique codes somewhere safe. If you forget your password, you can use ONE of these codes to log back into your account.',
    no_recovery_codes: 'No active recovery codes available. Please contact support.',
    issue_submitted_success: '✅ Issue submitted successfully',
    volunteers_notify_help: 'You will be notified if no volunteers are nearby.',
    resolving: 'Resolving...',
    username: 'Username',
    vol_dashboard_title: 'Volunteer Dashboard',
    welcome_helphub: 'Welcome to HelpHub! 🎉',
    setup_credentials_help: 'Please set up your permanent username and password.',
    username_placeholder: 'Choose a Username',
    password_placeholder: 'Choose a Password',
    save_continue: 'Save & Continue',
    step_1_confirm_loc: 'Step 1: Confirm Your Location',
    active_nav_point: 'Active Navigation Point',
    change_location: 'Change Location',
    search_location_volunteer: 'Search city/area manually',
    confirm_my_location_tasks: '✅ Confirm My Location & View Tasks',
    fetching_gps_help: 'Fetching initial GPS or awaiting manual search...',
    loading_tasks: 'Loading tasks securely...',
    your_tasks: 'Your Tasks',
    no_tasks_assigned: 'No tasks assigned to your name currently.',
    distance_to_issue: 'Distance to Issue',
    navigate: 'Navigate',
    user_contact_info: '📞 User Contact Information:',
    contact_info_requested: '📞 Contact Info Requested',
    pending_admin_approval: 'Pending admin approval.',
    contact_reason_label: 'Why do you need contact info?',
    submit_request_admin: 'Submit Request to Admin',
    cancel: 'Cancel',
    request_user_contact: '📞 Request User Contact Info',
    mark_resolved: '✅ Mark as Resolved (Attach Proof)',
    finalizing_resolution: 'Finalizing Resolution',
    upload_proof_help: 'Upload Picture or Video Proof',
    upload_resolve: '✅ Upload & Resolve',
    nearby_reports: 'Nearby Reports',
    no_nearby_issues: 'No pending nearby issues. Great job!',
    km_away: 'km away',
    view_map: '🗺️ View Map',
    request_assignment_btn: '✋ Request Assignment',
    your_requested_assignments: 'Your Requested Assignments',
    no_requested_assignments: 'No requests sent yet.',
    assignment_request_status: 'Assignment Request Status:',
    my_volunteer_profile: 'My Volunteer Profile',
    vol_account_id: 'Volunteer Account ID',
    full_name: 'Full Name',
    email_address: 'Email Address',
    city_location: 'City / Location',
  },
  te: {
    helphub: 'హెల్ప్‌హబ్',
    hero_title_1: 'నివేదించండి, పరిష్కరించండి,',
    hero_title_2: 'పునర్నిర్మించండి.',
    hero_subtitle: 'మీ ప్రాంతంలోని పౌర మరియు సంక్షేమ సమస్యలను నివేదించడానికి ఆధునిక మార్గం. మీ గొంతు వినిపించండి—అనామకంగా కూడా.',
    get_started: 'ప్రారంభించండి',
    subtitle: 'పౌర మరియు సంక్షేమ నివేదన వ్యవస్థ',
    select_language: 'భాషను ఎంచుకోండి',
    user_access: 'వినియోగదారు లాగిన్ / నమోదు',
    admin_access: 'అడ్మిన్',
    volunteer_access: 'వాలంటీర్ లాగిన్ / నమోదు',
    anonymous_report: 'అనామకంగా నివేదించండి',
    login: 'లాగిన్',
    register: 'నమోదు',
    report_issue: 'సమస్యను నివేదించండి',
    my_reports: 'నా నివేదికలు',
    emergency_call: 'అత్యవసర కాల్',
    instructions: 'సూచనలు / సహాయం',
    name: 'పేరు',
    phone: 'ఫోన్ నంబర్',
    age: 'వయస్సు',
    city: 'నగరం',
    email: 'ఇమెయిల్',
    password: 'పాస్‌వర్డ్',
    confirm_password: 'పాస్‌వర్డ్ నిర్ధారించండి',
    submit: 'సమర్పించండి',
    back: 'వెనక్కి',
    assistant_title: 'హెల్ప్‌హబ్ అసిస్టెంట్',
    assistant_subtitle: 'సాధారణ సమస్యలతో సహాయం పొందడానికి మా AI బోట్‌తో చాట్ చేయండి.',
    assistant_greeting: "నమస్కారం! నేను హెల్ప్‌హబ్ ఆటోమేటెడ్ అసిస్టెంట్‌ని. 'నేను చిత్రాన్ని అప్‌లోడ్ చేయలేకపోతున్నాను', 'లోకేషన్ పని చేయడం లేదు' లేదా 'సమస్యను ఎలా నివేదించాలి' వంటి ప్రశ్నలను మీరు నన్ను అడగవచ్చు. ఈరోజు నేను మీకు ఎలా సహాయపడగలను?",
    chat_placeholder: 'మీ ప్రశ్నను ఇక్కడ టైప్ చేయండి...',
    search_location: '📍 స్థానాన్ని వెతకండి',
    search_placeholder: 'నగరం లేదా ప్రాంతాన్ని టైప్ చేయండి (ఉదా: తిరుపతి, ఆంధ్రప్రదేశ్)',
    search_button: 'వెతకండి',
    searching: 'వెతుకుతున్నాము...',
    search_help_text: 'సబ్మిట్ చేసే ముందు మ్యాప్‌ను చూడటానికి మరియు కోఆర్డినేట్‌లను ధృవీకరించడానికి దయచేసి స్థానాన్ని వెతకండి.',
    confirmed: '📍 నిర్ధారించబడింది',
    re_enter_location: '✏️ స్థానాన్ని మళ్లీ నమోదు చేయండి',
    confirm_location_button: '✅ ఈ స్థానాన్ని నిర్ధారించండి',
    category: '🏷️ వర్గం',
    category_placeholder: 'ఉదా: జంతు సమస్య, రోడ్డు, వ్యర్థాలు...',
    upload_photo: '📸 ఫోటోను అప్‌లోడ్ చేయండి',
    voice_input: '🎤 వాయిస్ ఇన్‌పుట్',
    start_recording: 'రికార్డింగ్ ప్రారంభించండి',
    stop_recording: 'రికార్డింగ్ ఆపివేయండి',
    recording_status: 'రికార్డింగ్ అవుతోంది...',
    manual_input: '⌨️ మాన్యువల్ టెక్స్ట్ ఇన్‌పుట్',
    manual_input_placeholder: 'సమస్యను వివరంగా వివరించండి...',
    contact_info_label: 'సంప్రదింపు సమాచారాన్ని అందించండి (ఐచ్ఛికం)',
    contact_info_help: 'సమీపంలో వాలంటీర్లు లేకపోతే, ఈ సమస్యకు సంబంధించి అడ్మిన్ మిమ్మల్ని సంప్రదించవచ్చు.',
    contact_info_placeholder: 'ఇమెయిల్ లేదా ఫోన్ నంబర్',
    user_dashboard: 'యూజర్ డ్యాష్‌బోర్డ్',
    account_id: 'ఖాతా ఐడి',
    saving: 'పొందుపరుస్తున్నాము...',
    confirmed_coords: 'కోఆర్డినేట్‌లు',
    smart_suggestions: '✨ స్మార్ట్ సూచనలు (ఎంచుకోవడానికి క్లిక్ చేయండి)',
    selected_issue: 'ఎంచుకున్న సమస్య',
    converted_text: 'మార్చబడిన వచనం',
    strict_location_warning: 'నివేదికను సమర్పించే ముందు దయచేసి పైన మీ స్థానాన్ని ఖచ్చితంగా నిర్ధారించండి.',
    logout: 'లాగ్అవుట్',
    my_profile: 'నా ప్రొఫైల్',
    home: 'హోమ్',
    login_register: 'లాగిన్ / రిజిస్టర్',
    help_chat: 'సహాయం / చాట్',
    anonymous_report_nav: 'అనామక నివేదిక',
    assigned_issues: 'కేటాయించిన సమస్యలు',
    nearby_unassigned: 'సమీపంలోని కేటాయించనివి',
    requested_assignments: 'అభ్యర్థించిన కేటాయింపులు',
    issue_management: 'సమస్యల నిర్వహణ',
    volunteers: 'వాలంటీర్లు',
    assignment_requests: 'అసైన్‌మెంట్ అభ్యర్థనలు',
    emergency_call_nav: '🚨 అత్యవసర కాల్',
    report_an_issue_nav: 'సమస్యను నివేదించండి',
    loading_dashboard: 'డ్యాష్‌బోర్డ్ లోడ్ అవుతోంది...',
    selected_issue_label: 'ఎంచుకున్న సమస్య',
    date: 'తేదీ',
    admin_reply: 'అడ్మిన్ ప్రత్యుత్తరం',
    saving_changes: 'మార్పులను సేవ్ చేస్తున్నాము...',
    save_profile_details: 'ప్రొఫైల్ వివరాలను సేవ్ చేయండి',
    recovery_codes_title: 'ఖాతా రికవరీ కోడ్‌లు',
    hide: 'దాచు',
    reveal: 'చూపించు',
    recovery_codes_help: 'ఈ 4 రికవరీ కోడ్‌లను సురక్షితంగా దాచుకోండి. మీరు పాస్‌వర్డ్ మరిచిపోతే, మీ ఖాతాలోకి లాగిన్ అవ్వడానికి వీటిని ఉపయోగించవచ్చు.',
    no_recovery_codes: 'రికవరీ కోడ్‌లు అందుబాటులో లేవు. దయచేసి సహాయం కోసం సంప్రదించండి.',
    issue_submitted_success: '✅ సమస్య విజయవంతంగా సమర్పించబడింది',
    volunteers_notify_help: 'సమీపంలో వాలంటీర్లు లేకపోతే మీకు తెలియజేయబడుతుంది.',
    resolving: 'పరిష్కరిస్తున్నాము...',
    username: 'వినియోగదారు పేరు',
    vol_dashboard_title: 'వాలంటీర్ డ్యాష్‌బోర్డ్',
    welcome_helphub: 'హెల్ప్‌హబ్‌కు స్వాగతం! 🎉',
    setup_credentials_help: 'దయచేసి మీ శాశ్వత యూజర్ నేమ్ మరియు పాస్‌వర్డ్‌ను సెట్ చేసుకోండి.',
    username_placeholder: 'వినియోగదారు పేరును ఎంచుకోండి',
    password_placeholder: 'పాస్‌వర్డ్‌ను ఎంచుకోండి',
    save_continue: 'సేవ్ చేసి కొనసాగించండి',
    step_1_confirm_loc: 'దశ 1: మీ స్థానాన్ని నిర్ధారించండి',
    active_nav_point: 'క్రియాశీల నావిగేషన్ పాయింట్',
    change_location: 'స్థానాన్ని మార్చండి',
    search_location_volunteer: 'నగరం/ప్రాంతం కోసం వెతకండి',
    confirm_my_location_tasks: '✅ నా స్థానాన్ని నిర్ధారించి పనులను చూడండి',
    fetching_gps_help: 'GPS లేదా మాన్యువల్ సెర్చ్ కోసం వేచి చూస్తున్నాము...',
    loading_tasks: 'పనులను సురక్షితంగా లోడ్ చేస్తున్నాము...',
    your_tasks: 'మీ పనులు',
    no_tasks_assigned: 'ప్రస్తుతం మీ పేరు మీద ఏ పనులు లేవు.',
    distance_to_issue: 'సమస్యకు దూరం',
    navigate: 'నావిగేట్ చేయండి',
    user_contact_info: '📞 యూజర్ సంప్రదింపు సమాచారం:',
    contact_info_requested: '📞 సంప్రదింపు సమాచారం అభ్యర్థించబడింది',
    pending_admin_approval: 'అడ్మిన్ ఆమోదం కోసం వేచి ఉంది.',
    contact_reason_label: 'సంప్రదింపు సమాచారం మీకు ఎందుకు అవసరం?',
    submit_request_admin: 'అడ్మిన్‌కు అభ్యర్థనను పంపండి',
    cancel: 'రద్దు చేయండి',
    request_user_contact: '📞 యూజర్ సంప్రదింపు సమాచారాన్ని అభ్యర్థించండి',
    mark_resolved: '✅ పరిష్కరించబడినట్లు గుర్తించండి (సాక్ష్యం జత చేయండి)',
    finalizing_resolution: 'పరిష్కారాన్ని పూర్తి చేస్తున్నాము',
    upload_proof_help: 'చిత్రం లేదా వీడియో సాక్ష్యాన్ని అప్‌లోడ్ చేయండి',
    upload_resolve: '✅ అప్‌లోడ్ చేసి పరిష్కరించండి',
    nearby_reports: 'సమీప నివేదికలు',
    no_nearby_issues: 'సమీపంలో పెండింగ్‌లో ఉన్న సమస్యలు లేవు. అభినందనలు!',
    km_away: 'కి.మీ దూరంలో',
    view_map: '🗺️ మ్యాప్‌ను చూడండి',
    request_assignment_btn: '✋ పనిని అభ్యర్థించండి',
    your_requested_assignments: 'మీరు అభ్యర్థించిన పనులు',
    no_requested_assignments: 'ఇంకా ఎటువంటి అభ్యర్థనలు పంపలేదు.',
    assignment_request_status: 'పని అభ్యర్థన స్థితి:',
    my_volunteer_profile: 'నా వాలంటీర్ ప్రొఫైల్',
    vol_account_id: 'వాలంటీర్ ఖాతా ఐడి',
    full_name: 'పూర్తి పేరు',
    email_address: 'ఇమెయిల్ చిరునామా',
    city_location: 'నగరం / స్థానం',
  },
  ta: {
    helphub: 'ஹெல்ப்ஹப்',
    hero_title_1: 'புகாரளி, தீர்,',
    hero_title_2: 'மீண்டும் உருவாக்கு.',
    hero_subtitle: 'உங்கள் பகுதியில் உள்ள குடிமக்கள் மற்றும் நலன்புரி பிரச்சனைகளை புகாரளிப்பதற்கான நவீன வழி. அநாமதேயமாக இருந்தாலும் உங்கள் குரல் கேட்கட்டும்.',
    get_started: 'தொடங்குங்கள்',
    subtitle: 'குடிமக்கள் மற்றும் நலன்புரி அறிக்கை அமைப்பு',
    select_language: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    user_access: 'பயனர் உள்நுழைவு / பதிவு',
    admin_access: 'நிர்வாகி',
    volunteer_access: 'தன்னார்வலர் உள்நுழைவு / பதிவு',
    anonymous_report: 'அநாமதேயமாக புகாரளிக்கவும்',
    login: 'உள்நுழைக',
    register: 'பதிவு செய்',
    report_issue: 'பிரச்சனையை புகாரளிக்கவும்',
    my_reports: 'என் அறிக்கைகள்',
    emergency_call: 'அவசர அழைப்பு',
    instructions: 'வழிமுறைகள் / உதவி',
    name: 'பெயர்',
    phone: 'தொலைபேசி எண்',
    age: 'வயது',
    city: 'நகரம்',
    email: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    confirm_password: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    submit: 'சமர்ப்பி',
    back: 'திரும்பவும்',
    assistant_title: 'ஹெல்ப்ஹப் உதவியாளர்',
    assistant_subtitle: 'பொதுவான சிக்கல்களுக்கு உதவி பெற எங்கள் AI போட் மூலம் அரட்டையடிக்கவும்.',
    assistant_greeting: "வணக்கம்! நான் ஹெல்ப்ஹப்பின் தானியங்கி உதவியாளர். 'என்னால் படத்தை பதிவேற்ற முடியவில்லை', 'இருப்பிடம் வேலை செய்யவில்லை' அல்லது 'பிரச்சனையை எப்படி புகாரளிப்பது' போன்ற கேள்விகளை நீங்கள் என்னிடம் கேட்கலாம். இன்று நான் உங்களுக்கு எப்படி உதவ முடியும்?",
    chat_placeholder: 'உங்கள் கேள்வியை இங்கே தட்டச்சு செய்க...',
    search_location: '📍 இருப்பிடத்தைத் தேடு',
    search_placeholder: 'நகரம் அல்லது பகுதியைத் தட்டச்சு செய்க (எ.கா: சென்னை, தமிழ்நாடு)',
    search_button: 'தேடு',
    searching: 'தேடுகிறது...',
    search_help_text: 'சமர்ப்பிக்கும் முன் வரைபடத்தைப் பார்க்கவும் உங்கள் ஒருங்கிணைப்புகளைச் சரிபார்க்கவும் இருப்பிடத்தைத் தேடவும்.',
    confirmed: '📍 உறுதிப்படுத்தப்பட்டது',
    re_enter_location: '✏️ இருப்பிடத்தை மீண்டும் உள்ளிடவும்',
    confirm_location_button: '✅ இந்த இருப்பிடத்தை உறுதிப்படுத்தவும்',
    category: '🏷️ வகை',
    category_placeholder: 'எ.கா. விலங்கு பிரச்சனை, சாலை, கழிவு...',
    upload_photo: '📸 புகைப்படத்தைப் பதிவேற்றவும்',
    voice_input: '🎤 குரல் உள்ளீடு',
    start_recording: 'பதிவைத் தொடங்கவும்',
    stop_recording: 'பதிவை நிறுத்தவும்',
    recording_status: 'பதிவு செய்யப்படுகிறது...',
    manual_input: '⌨️ கைமுறை உரை உள்ளீடு',
    manual_input_placeholder: 'சிக்கலை விரிவாக விவரிக்கவும்...',
    contact_info_label: 'தொடர்புத் தகவலை விடவும் (விருப்பத்தேர்வு)',
    contact_info_help: 'அருகில் தன்னார்வலர்கள் யாரும் இல்லையென்றால், இந்த சிக்கல் தொடர்பாக நிர்வாகி உங்களைத் தொடர்பு கொள்ளலாம்.',
    contact_info_placeholder: 'மின்னஞ்சல் அல்லது தொலைபேசி எண்',
    user_dashboard: 'பயனர் டாஷ்போர்டு',
    account_id: 'கணக்கு ஐடி',
    saving: 'சேமிக்கிறது...',
    confirmed_coords: 'ஒருங்கிணைப்புகள்',
    smart_suggestions: '✨ ஸ்மார்ட் பரிந்துரைகள் (தேர்ந்தெடுக்க கிளிக் செய்யவும்)',
    selected_issue: 'தேர்ந்தெடுக்கப்பட்ட சிக்கல்',
    converted_text: 'மாற்றப்பட்ட உரை',
    strict_location_warning: 'அறிக்கையைச் சமர்ப்பிக்கும் முன் மேலே உள்ள உங்கள் இருப்பிடத்தை உறுதிப்படுத்தவும்.',
    logout: 'வெளியேறு',
    my_profile: 'என் சுயவிவரம்',
    home: 'முகப்பு',
    login_register: 'உள்நுழைவு / பதிவு',
    help_chat: 'உதவி / அரட்டை',
    anonymous_report_nav: 'அநாமதேய அறிக்கை',
    assigned_issues: 'ஒதுக்கப்பட்ட சிக்கல்கள்',
    nearby_unassigned: 'அருகிலுள்ள ஒதுக்கப்படாதவை',
    requested_assignments: 'கோரப்பட்ட பணிகள்',
    issue_management: 'சிக்கல் மேலாண்மை',
    volunteers: 'தன்னார்வலர்கள்',
    assignment_requests: 'பணி ஒதுக்கீடு கோரிக்கைகள்',
    emergency_call_nav: '🚨 அவசர அழைப்பு',
    report_an_issue_nav: 'பிரச்சனையை புகாரளிக்கவும்',
    loading_dashboard: 'டாஷ்போர்டு ஏற்றப்படுகிறது...',
    selected_issue_label: 'தேர்ந்தெடுக்கப்பட்ட பிரச்சனை',
    date: 'தேதி',
    admin_reply: 'நிர்வாகியின் பதில்',
    saving_changes: 'மாற்றங்களைச் சேமிக்கிறது...',
    save_profile_details: 'சுயவிவர விவரங்களைச் சேமிக்கவும்',
    recovery_codes_title: 'கணக்கு மீட்பு குறியீடுகள்',
    hide: 'மறைக்கவும்',
    reveal: 'காண்பிக்கவும்',
    recovery_codes_help: 'இந்த 4 மீட்பு குறியீடுகளையும் பாதுகாப்பாக சேமிக்கவும். உங்கள் கடவுச்சொல்லை மறந்துவிட்டால், இவற்றைப் பயன்படுத்தி லாகின் செய்யலாம்.',
    no_recovery_codes: 'மீட்பு குறியீடுகள் எதுவும் இல்லை. தயவுசெய்து எங்களைத் தொடர்பு கொள்ளவும்.',
    issue_submitted_success: '✅ பிரச்சனை வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது',
    volunteers_notify_help: 'அருகில் தன்னார்வலர்கள் யாரும் இல்லையென்றால் உங்களுக்குத் தெரிவிக்கப்படும்.',
    resolving: 'தீர்வு காணப்படுகிறது...',
    username: 'பயனர் பெயர்',
    vol_dashboard_title: 'தன்னார்வலர் டாஷ்போர்டு',
    welcome_helphub: 'ஹெல்ப்ஹப்பிற்கு வரவேற்கிறோம்! 🎉',
    setup_credentials_help: 'உங்கள் நிரந்தர பயனர் பெயர் மற்றும் கடவுச்சொல்லை அமைக்கவும்.',
    username_placeholder: 'பயனர் பெயரைத் தேர்ந்தெடுக்கவும்',
    password_placeholder: 'கடவுச்சொல்லைத் தேர்ந்தெடுக்கவும்',
    save_continue: 'சேமிக்கவும் & தொடரவும்',
    step_1_confirm_loc: 'படி 1: உங்கள் இருப்பிடத்தை உறுதிப்படுத்தவும்',
    active_nav_point: 'செயலில் உள்ள வழிசெலுத்தல் புள்ளி',
    change_location: 'இருப்பிடத்தை மாற்றவும்',
    search_location_volunteer: 'நகரம்/பகுதியைத் தேடவும்',
    confirm_my_location_tasks: '✅ என் இருப்பிடத்தை உறுதிசெய்து பணிகளைப் பார்க்கவும்',
    fetching_gps_help: 'GPS அல்லது கைமுறை தேடலுக்காக காத்திருக்கிறது...',
    loading_tasks: 'பணிகள் பாதுகாப்பாக ஏற்றப்படுகின்றன...',
    your_tasks: 'உங்கள் பணிகள்',
    no_tasks_assigned: 'தற்போது உங்கள் பெயரில் எந்தப் பணிகளும் இல்லை.',
    distance_to_issue: 'பிரச்சனைக்கான தூரம்',
    navigate: 'வழிசெலுத்து',
    user_contact_info: '📞 பயனர் தொடர்பு விவரங்கள்:',
    contact_info_requested: '📞 தொடர்பு விவரங்கள் கோரப்பட்டுள்ளன',
    pending_admin_approval: 'நிர்வாகியின் ஒப்புதலுக்காகக் காத்திருக்கிறது.',
    contact_reason_label: 'தொடர்பு விவரங்கள் ஏன் தேவை?',
    submit_request_admin: 'நிர்வாகிக்கு கோரிக்கையை அனுப்பவும்',
    cancel: 'ரத்து செய்',
    request_user_contact: '📞 பயனர் தொடர்பு விவரங்களைக் கோரவும்',
    mark_resolved: '✅ தீர்க்கப்பட்டதாகக் குறிக்கவும் (சான்றை இணைக்கவும்)',
    finalizing_resolution: 'முடிவு எடுக்கப்படுகிறது',
    upload_proof_help: 'புகைப்படம் அல்லது வீடியோ சான்றைப் பதிவேற்றவும்',
    upload_resolve: '✅ பதிவேற்றவும் & தீர்க்கவும்',
    nearby_reports: 'அருகிலுள்ள அறிக்கைகள்',
    no_nearby_issues: 'அருகில் நிலுவையில் உள்ள சிக்கல்கள் எதுவும் இல்லை. நன்று!',
    km_away: 'கி.மீ தூரத்தில்',
    view_map: '🗺️ வரைபடத்தைப் பார்க்கவும்',
    request_assignment_btn: '✋ பணியைக் கோரவும்',
    your_requested_assignments: 'நீங்கள் கோரிய பணிகள்',
    no_requested_assignments: 'இன்னும் எந்த கோரிக்கைகளும் அனுப்பப்படவில்லை.',
    assignment_request_status: 'பணி கோரிக்கை நிலை:',
    my_volunteer_profile: 'என் தன்னார்வலர் சுயவிவரம்',
    vol_account_id: 'தன்னார்வலர் கணக்கு ஐடி',
    full_name: 'முழு பெயர்',
    email_address: 'மின்னஞ்சல் முகவரி',
    city_location: 'நகரம் / இருப்பிடம்',
  },
  hi: {
    helphub: 'हेल्पहब',
    hero_title_1: 'रिपोर्ट करें, समाधान करें,',
    hero_title_2: 'पुनर्निर्माण करें।',
    hero_subtitle: 'अपने पड़ोस में नागरिक और कल्याणकारी मुद्दों की रिपोर्ट करने का आधुनिक तरीका। अपनी आवाज़ सुनाएँ—भले ही गुमनाम रूप से।',
    get_started: 'शुरू करें',
    subtitle: 'नागरिक और कल्याण रिपोर्टिंग प्रणाली',
    select_language: 'भाषा चुनें',
    user_access: 'उपयोगकर्ता लॉगिन / पंजीकरण',
    admin_access: 'व्यवस्थापक',
    volunteer_access: 'स्वयंसेवक लॉगिन / पंजीकरण',
    anonymous_report: 'गुमनाम रूप से रिपोर्ट करें',
    login: 'लॉग इन करें',
    register: 'पंजीकरण करें',
    report_issue: 'समस्या की रिपोर्ट करें',
    my_reports: 'मेरी रिपोर्ट',
    emergency_call: 'आपातकालीन कॉल',
    instructions: 'निर्देश / सहायता',
    name: 'नाम',
    phone: 'फ़ोन नंबर',
    age: 'आयु',
    city: 'शहर',
    email: 'ईमेल',
    password: 'पासवर्ड',
    confirm_password: 'पासवर्ड की पुष्टि करें',
    submit: 'जमा करें',
    back: 'वापस',
    assistant_title: 'हेल्पहब सहायक',
    assistant_subtitle: 'सामान्य समस्याओं में सहायता पाने के लिए हमारे AI बॉट के साथ चैट करें।',
    assistant_greeting: "नमस्ते! मैं हेल्पहब का स्वचालित सहायक हूँ। आप मुझसे 'मैं छवि अपलोड नहीं कर पा रहा हूँ', 'स्थान काम नहीं कर रहा है', या 'समस्या की रिपोर्ट कैसे करें' जैसे प्रश्न पूछ सकते हैं। आज मैं आपकी क्या सहायता कर सकता हूँ?",
    chat_placeholder: 'अपना प्रश्न यहाँ टाइप करें...',
    search_location: '📍 स्थान खोजें',
    search_placeholder: 'शहर या क्षेत्र टाइप करें (जैसे तिरुपति, आंध्र प्रदेश)',
    search_button: 'खोजें',
    searching: 'खोज रहे हैं...',
    search_help_text: 'रिपोर्ट जमा करने से पहले मानचित्र देखने और अपने स्थान की पुष्टि करने के लिए कृपया स्थान खोजें।',
    confirmed: '📍 पुष्टि की गई',
    re_enter_location: '✏️ स्थान फिर से दर्ज करें',
    confirm_location_button: '✅ इस स्थान की पुष्टि करें',
    category: '🏷️ श्रेणी',
    category_placeholder: 'जैसे पशु मुद्दा, सड़क, कचरा...',
    upload_photo: '📸 फोटो अपलोड करें',
    voice_input: '🎤 वॉयस इनपुट',
    start_recording: 'रिकॉर्डिंग शुरू करें',
    stop_recording: 'रिकॉर्डिंग बंद करें',
    recording_status: 'रिकॉर्डिंग हो रही है...',
    manual_input: '⌨️ मैनुअल टेक्स्ट इनपुट',
    manual_input_placeholder: 'समस्या का विस्तार से वर्णन करें...',
    contact_info_label: 'संपर्क जानकारी छोड़ें (वैकल्पिक)',
    contact_info_help: 'यदि आस-पास कोई स्वयंसेवक नहीं है, तो व्यवस्थापक इस मुद्दे के संबंध में आपसे संपर्क कर सकता है।',
    contact_info_placeholder: 'ईमेल या फ़ोन नंबर',
    user_dashboard: 'उपयोगकर्ता डैशबोर्ड',
    account_id: 'खाता आईडी',
    saving: 'सहेज रहा है...',
    confirmed_coords: 'निर्देशांक',
    smart_suggestions: '✨ स्मार्ट सुझाव (चुनने के लिए क्लिक करें)',
    selected_issue: 'चयनित मुद्दा',
    converted_text: 'परिवर्तित पाठ',
    strict_location_warning: 'रिपोर्ट जमा करने से पहले कृपया ऊपर अपना स्थान स्पष्ट रूप से पुष्टि करें।',
    logout: 'लॉगआउट',
    my_profile: 'मेरी प्रोफाइल',
    home: 'होम',
    login_register: 'लॉगिन / रजिस्टर',
    help_chat: 'सहायता / चैट',
    anonymous_report_nav: 'गुमनाम रिपोर्ट',
    assigned_issues: 'आवंटित मुद्दे',
    nearby_unassigned: 'पास के गैर-आवंटित',
    requested_assignments: 'अनुरोधित असाइनमेंट',
    issue_management: 'मुद्दा प्रबंधन',
    volunteers: 'स्वयंसेवक',
    assignment_requests: 'असाइनमेंट अनुरोध',
    emergency_call_nav: '🚨 आपातकालीन कॉल',
    report_an_issue_nav: 'समस्या की रिपोर्ट करें',
    loading_dashboard: 'डैशबोर्ड लोड हो रहा है...',
    selected_issue_label: 'चयनित मुद्दा',
    date: 'तारीख',
    admin_reply: 'व्यवस्थापक का उत्तर',
    saving_changes: 'परिवर्तन सहेजे जा रहे हैं...',
    save_profile_details: 'प्रोफ़ाइल विवरण सहेजें',
    recovery_codes_title: 'खाता रिकवरी कोड',
    hide: 'छिपाएं',
    reveal: 'दिखाएं',
    recovery_codes_help: 'इन 4 रिकवरी कोड को सुरक्षित रखें। यदि आप पासवर्ड भूल जाते हैं, तो आप इनका उपयोग करके लॉग इन कर सकते हैं।',
    no_recovery_codes: 'कोई रिकवरी कोड उपलब्ध नहीं है। कृपया सहायता के लिए संपर्क करें।',
    issue_submitted_success: '✅ समस्या सफलतापूर्वक जमा हो गई',
    volunteers_notify_help: 'यदि आसपास कोई स्वयंसेवक नहीं हैं तो आपको सूचित किया जाएगा.',
    resolving: 'समाधान हो रहा है...',
    username: 'उपयोगकर्ता नाम',
    vol_dashboard_title: 'स्वयंसेवक डैशबोर्ड',
    welcome_helphub: 'हेल्पहब में आपका स्वागत है! 🎉',
    setup_credentials_help: 'कृपया अपना स्थायी उपयोगकर्ता नाम और पासवर्ड सेट करें।',
    username_placeholder: 'उपयोगकर्ता नाम चुनें',
    password_placeholder: 'पासवर्ड चुनें',
    save_continue: 'सहेजें और जारी रखें',
    step_1_confirm_loc: 'चरण 1: अपने स्थान की पुष्टि करें',
    active_nav_point: 'सक्रिय नेविगेशन बिंदु',
    change_location: 'स्थान बदलें',
    search_location_volunteer: 'शहर/क्षेत्र खोजें',
    confirm_my_location_tasks: '✅ अपने स्थान की पुष्टि करें और कार्य देखें',
    fetching_gps_help: 'GPS या मैन्युअल खोज की प्रतीक्षा है...',
    loading_tasks: 'कार्य सुरक्षित रूप से लोड हो रहे हैं...',
    your_tasks: 'आपके कार्य',
    no_tasks_assigned: 'वर्तमान में आपके नाम पर कोई कार्य आवंटित नहीं है।',
    distance_to_issue: 'समस्या की दूरी',
    navigate: 'नेविगेट करें',
    user_contact_info: '📞 उपयोगकर्ता संपर्क जानकारी:',
    contact_info_requested: '📞 संपर्क जानकारी मांगी गई',
    pending_admin_approval: 'व्यवस्थापक की मंजूरी का इंतज़ार है।',
    contact_reason_label: 'संपर्क जानकारी क्यों आवश्यक है?',
    submit_request_admin: 'व्यवस्थापक को अनुरोध भेजें',
    cancel: 'रद्द करें',
    request_user_contact: '📞 उपयोगकर्ता संपर्क जानकारी का अनुरोध करें',
    mark_resolved: '✅ समाधान के रूप में चिह्नित करें (प्रमाण जोड़ें)',
    finalizing_resolution: 'समाधान को अंतिम रूप दे रहे हैं',
    upload_proof_help: 'चित्र या वीडियो प्रमाण अपलोड करें',
    upload_resolve: '✅ अपलोड करें और समाधान करें',
    nearby_reports: 'आस-पास की रिपोर्ट',
    no_nearby_issues: 'आस-पास कोई लंबित समस्या नहीं है। बहुत बढ़िया!',
    km_away: 'किमी दूर',
    view_map: '🗺️ मानचित्र देखें',
    request_assignment_btn: '✋ असाइनमेंट का अनुरोध करें',
    your_requested_assignments: 'आपके अनुरोधित असाइनमेंट',
    no_requested_assignments: 'अभी तक कोई अनुरोध नहीं भेजा गया है।',
    assignment_request_status: 'असाइनमेंट अनुरोध स्थिति:',
    my_volunteer_profile: 'मेरी स्वयंसेवक प्रोफ़ाइल',
    vol_account_id: 'स्वयंसेवक खाता आईडी',
    full_name: 'पूरा नाम',
    email_address: 'ईमेल पता',
    city_location: 'शहर / स्थान',
  }
};

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('helphub_lang') as Language;
    if (saved && translations[saved]) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    localStorage.setItem('helphub_lang', lang);
    setLanguageState(lang);
  };

  const t = (key: string) => {
    return translations[language as Language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
