'use client';

import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'en' | 'te' | 'ta' | 'hi';

interface Dictionary {
  [key: string]: string;
}

const translations: Record<Language, Dictionary> = {
  en: {
    helphub: 'HelpHub',
    hero_title_1: 'Report, Resolve,',
    hero_title_2: 'Rebuild.',
    hero_subtitle: 'The modern way to report civic and welfare issues in your neighborhood. From potholes to public safety, let your voice be heard—even anonymously.',
    get_started: 'Get Started',
    subtitle: 'Civic and Welfare Reporting System',
    select_language: 'Select Language',
    user_access: 'User Login / Register',
    admin_access: 'Admin',
    volunteer_access: 'Volunteer Login / Register',
    anonymous_report: 'Report Anonymously',
    login: 'Login',
    register: 'Register',
    report_issue: 'Report an Issue',
    my_reports: 'My Reports',
    emergency_call: 'Emergency Call',
    instructions: 'Instructions / Help',
    name: 'Name',
    phone: 'Phone Number',
    age: 'Age',
    city: 'City',
    email: 'Email',
    password: 'Password',
    confirm_password: 'Confirm Password',
    submit: 'Submit',
    back: 'Back',
    assistant_title: 'HelpHub Assistant',
    assistant_subtitle: 'Chat with our AI bot to get help with common issues.',
    assistant_greeting: "Hello! I am HelpHub's automated assistant. You can ask me questions like 'I can't upload image', 'location not working', or 'how to report issue'. How can I help you today?",
    chat_placeholder: 'Type your question here...',
    search_location: '📍 Search Location',
    search_placeholder: 'Type city or area (e.g. Tirupati, Andhra Pradesh)',
    search_button: 'Search',
    searching: 'Searching...',
    search_help_text: 'Please search for a location to view the map and verify your coordinates before submitting.',
    confirmed: '📍 Confirmed',
    re_enter_location: '✏️ Re-enter location',
    confirm_location_button: '✅ Confirm This Location',
    category: '🏷️ Category',
    category_placeholder: 'e.g. Animal Issue, Road, Waste...',
    upload_photo: '📸 Upload Photo',
    voice_input: '🎤 Voice Input',
    start_recording: 'Start Recording',
    stop_recording: 'Stop Recording',
    recording_status: 'Recording...',
    manual_input: '⌨️ Manual Text Input',
    manual_input_placeholder: 'Describe the issue in detail...',
    contact_info_label: 'Leave Contact Info (Optional)',
    contact_info_help: 'If there are no nearby volunteers, an admin can contact you regarding this issue.',
    contact_info_placeholder: 'Email or Phone Number',
    user_dashboard: 'User Dashboard',
    account_id: 'Account ID',
    saving: 'Saving...',
    confirmed_coords: 'Coordinates',
    smart_suggestions: '✨ Smart Suggestions (Click to select)',
    selected_issue: 'Selected Issue',
    converted_text: 'Converted Text',
    strict_location_warning: 'Please strictly confirm your location above before submitting a report.',
    logout: 'Logout',
    my_profile: 'My Profile',
  },
  te: {
    helphub: 'హెల్ప్‌హబ్',
    hero_title_1: 'నివేదించండి, పరిష్కరించండి,',
    hero_title_2: 'పునర్నిర్మించండి.',
    hero_subtitle: 'మీ ప్రాంతంలోని పౌర మరియు సంక్షేమ సమస్యలను నివేదించడానికి ఆధునిక మార్గం. మీ గొంతు వినిపించండి—అనామకంగా కూడా.',
    get_started: 'ప్రారంభించండి',
    subtitle: 'పౌర మరియు సంక్షేమ నివేదన వ్యవస్థ',
    select_language: 'భాషను ఎంచుకోండి',
    user_access: 'వినియోగదారు లాగిన్ / నమోదు',
    admin_access: 'అడ్మిన్',
    volunteer_access: 'వాలంటీర్ లాగిన్ / నమోదు',
    anonymous_report: 'అనామకంగా నివేదించండి',
    login: 'లాగిన్',
    register: 'నమోదు',
    report_issue: 'సమస్యను నివేదించండి',
    my_reports: 'నా నివేదికలు',
    emergency_call: 'అత్యవసర కాల్',
    instructions: 'సూచనలు / సహాయం',
    name: 'పేరు',
    phone: 'ఫోన్ నంబర్',
    age: 'వయస్సు',
    city: 'నగరం',
    email: 'ఇమెయిల్',
    password: 'పాస్‌వర్డ్',
    confirm_password: 'పాస్‌వర్డ్ నిర్ధారించండి',
    submit: 'సమర్పించండి',
    back: 'వెనక్కి',
    assistant_title: 'హెల్ప్‌హబ్ అసిస్టెంట్',
    assistant_subtitle: 'సాధారణ సమస్యలతో సహాయం పొందడానికి మా AI బోట్‌తో చాట్ చేయండి.',
    assistant_greeting: "నమస్కారం! నేను హెల్ప్‌హబ్ ఆటోమేటెడ్ అసిస్టెంట్‌ని. 'నేను చిత్రాన్ని అప్‌లోడ్ చేయలేకపోతున్నాను', 'లోకేషన్ పని చేయడం లేదు' లేదా 'సమస్యను ఎలా నివేదించాలి' వంటి ప్రశ్నలను మీరు నన్ను అడగవచ్చు. ఈరోజు నేను మీకు ఎలా సహాయపడగలను?",
    chat_placeholder: 'మీ ప్రశ్నను ఇక్కడ టైప్ చేయండి...',
    search_location: '📍 స్థానాన్ని వెతకండి',
    search_placeholder: 'నగరం లేదా ప్రాంతాన్ని టైప్ చేయండి (ఉదా: తిరుపతి, ఆంధ్రప్రదేశ్)',
    search_button: 'వెతకండి',
    searching: 'వెతుకుతున్నాము...',
    search_help_text: 'సబ్మిట్ చేసే ముందు మ్యాప్‌ను చూడటానికి మరియు కోఆర్డినేట్‌లను ధృవీకరించడానికి దయచేసి స్థానాన్ని వెతకండి.',
    confirmed: '📍 నిర్ధారించబడింది',
    re_enter_location: '✏️ స్థానాన్ని మళ్లీ నమోదు చేయండి',
    confirm_location_button: '✅ ఈ స్థానాన్ని నిర్ధారించండి',
    category: '🏷️ వర్గం',
    category_placeholder: 'ఉదా: జంతు సమస్య, రోడ్డు, వ్యర్థాలు...',
    upload_photo: '📸 ఫోటోను అప్‌లోడ్ చేయండి',
    voice_input: '🎤 వాయిస్ ఇన్‌పుట్',
    start_recording: 'రికార్డింగ్ ప్రారంభించండి',
    stop_recording: 'రికార్డింగ్ ఆపివేయండి',
    recording_status: 'రికార్డింగ్ అవుతోంది...',
    manual_input: '⌨️ మాన్యువల్ టెక్స్ట్ ఇన్‌పుట్',
    manual_input_placeholder: 'సమస్యను వివరంగా వివరించండి...',
    contact_info_label: 'సంప్రదింపు సమాచారాన్ని అందించండి (ఐచ్ఛికం)',
    contact_info_help: 'సమీపంలో వాలంటీర్లు లేకపోతే, ఈ సమస్యకు సంబంధించి అడ్మిన్ మిమ్మల్ని సంప్రదించవచ్చు.',
    contact_info_placeholder: 'ఇమెయిల్ లేదా ఫోన్ నంబర్',
    user_dashboard: 'యూజర్ డ్యాష్‌బోర్డ్',
    account_id: 'ఖాతా ఐడి',
    saving: 'పొందుపరుస్తున్నాము...',
    confirmed_coords: 'కోఆర్డినేట్‌లు',
    smart_suggestions: '✨ స్మార్ట్ సూచనలు (ఎంచుకోవడానికి క్లిక్ చేయండి)',
    selected_issue: 'ఎంచుకున్న సమస్య',
    converted_text: 'మార్చబడిన వచనం',
    strict_location_warning: 'నివేదికను సమర్పించే ముందు దయచేసి పైన మీ స్థానాన్ని ఖచ్చితంగా నిర్ధారించండి.',
    logout: 'లాగ్అవుట్',
    my_profile: 'నా ప్రొఫైల్',
  },
  ta: {
    helphub: 'ஹெல்ப்ஹப்',
    hero_title_1: 'புகாரளி, தீர்,',
    hero_title_2: 'மீண்டும் உருவாக்கு.',
    hero_subtitle: 'உங்கள் பகுதியில் உள்ள குடிமக்கள் மற்றும் நலன்புரி பிரச்சனைகளை புகாரளிப்பதற்கான நவீன வழி. அநாமதேயமாக இருந்தாலும் உங்கள் குரல் கேட்கட்டும்.',
    get_started: 'தொடங்குங்கள்',
    subtitle: 'குடிமக்கள் மற்றும் நலன்புரி அறிக்கை அமைப்பு',
    select_language: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    user_access: 'பயனர் உள்நுழைவு / பதிவு',
    admin_access: 'நிர்வாகி',
    volunteer_access: 'தன்னார்வலர் உள்நுழைவு / பதிவு',
    anonymous_report: 'அநாமதேயமாக புகாரளிக்கவும்',
    login: 'உள்நுழைக',
    register: 'பதிவு செய்',
    report_issue: 'பிரச்சனையை புகாரளிக்கவும்',
    my_reports: 'என் அறிக்கைகள்',
    emergency_call: 'அவசர அழைப்பு',
    instructions: 'வழிமுறைகள் / உதவி',
    name: 'பெயர்',
    phone: 'தொலைபேசி எண்',
    age: 'வயது',
    city: 'நகரம்',
    email: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    confirm_password: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    submit: 'சமர்ப்பி',
    back: 'திரும்பவும்',
    assistant_title: 'ஹெல்ப்ஹப் உதவியாளர்',
    assistant_subtitle: 'பொதுவான சிக்கல்களுக்கு உதவி பெற எங்கள் AI போட் மூலம் அரட்டையடிக்கவும்.',
    assistant_greeting: "வணக்கம்! நான் ஹெல்ப்ஹப்பின் தானியங்கி உதவியாளர். 'என்னால் படத்தை பதிவேற்ற முடியவில்லை', 'இருப்பிடம் வேலை செய்யவில்லை' அல்லது 'பிரச்சனையை எப்படி புகாரளிப்பது' போன்ற கேள்விகளை நீங்கள் என்னிடம் கேட்கலாம். இன்று நான் உங்களுக்கு எப்படி உதவ முடியும்?",
    chat_placeholder: 'உங்கள் கேள்வியை இங்கே தட்டச்சு செய்க...',
    search_location: '📍 இருப்பிடத்தைத் தேடு',
    search_placeholder: 'நகரம் அல்லது பகுதியைத் தட்டச்சு செய்க (எ.கா: சென்னை, தமிழ்நாடு)',
    search_button: 'தேடு',
    searching: 'தேடுகிறது...',
    search_help_text: 'சமர்ப்பிக்கும் முன் வரைபடத்தைப் பார்க்கவும் உங்கள் ஒருங்கிணைப்புகளைச் சரிபார்க்கவும் இருப்பிடத்தைத் தேடவும்.',
    confirmed: '📍 உறுதிப்படுத்தப்பட்டது',
    re_enter_location: '✏️ இருப்பிடத்தை மீண்டும் உள்ளிடவும்',
    confirm_location_button: '✅ இந்த இருப்பிடத்தை உறுதிப்படுத்தவும்',
    category: '🏷️ வகை',
    category_placeholder: 'எ.கா. விலங்கு பிரச்சனை, சாலை, கழிவு...',
    upload_photo: '📸 புகைப்படத்தைப் பதிவேற்றவும்',
    voice_input: '🎤 குரல் உள்ளீடு',
    start_recording: 'பதிவைத் தொடங்கவும்',
    stop_recording: 'பதிவை நிறுத்தவும்',
    recording_status: 'பதிவு செய்யப்படுகிறது...',
    manual_input: '⌨️ கைமுறை உரை உள்ளீடு',
    manual_input_placeholder: 'சிக்கலை விரிவாக விவரிக்கவும்...',
    contact_info_label: 'தொடர்புத் தகவலை விடவும் (விருப்பத்தேர்வு)',
    contact_info_help: 'அருகில் தன்னார்வலர்கள் யாரும் இல்லையென்றால், இந்த சிக்கல் தொடர்பாக நிர்வாகி உங்களைத் தொடர்பு கொள்ளலாம்.',
    contact_info_placeholder: 'மின்னஞ்சல் அல்லது தொலைபேசி எண்',
    user_dashboard: 'பயனர் டாஷ்போர்டு',
    account_id: 'கணக்கு ஐடி',
    saving: 'சேமிக்கிறது...',
    confirmed_coords: 'ஒருங்கிணைப்புகள்',
    smart_suggestions: '✨ ஸ்மார்ட் பரிந்துரைகள் (தேர்ந்தெடுக்க கிளிக் செய்யவும்)',
    selected_issue: 'தேர்ந்தெடுக்கப்பட்ட சிக்கல்',
    converted_text: 'மாற்றப்பட்ட உரை',
    strict_location_warning: 'அறிக்கையைச் சமர்ப்பிக்கும் முன் மேலே உள்ள உங்கள் இருப்பிடத்தை உறுதிப்படுத்தவும்.',
    logout: 'வெளியேறு',
    my_profile: 'என் சுயவிவரம்',
  },
  hi: {
    helphub: 'हेल्पहब',
    hero_title_1: 'रिपोर्ट करें, समाधान करें,',
    hero_title_2: 'पुनर्निर्माण करें।',
    hero_subtitle: 'अपने पड़ोस में नागरिक और कल्याणकारी मुद्दों की रिपोर्ट करने का आधुनिक तरीका। अपनी आवाज़ सुनाएँ—भले ही गुमनाम रूप से।',
    get_started: 'शुरू करें',
    subtitle: 'नागरिक और कल्याण रिपोर्टिंग प्रणाली',
    select_language: 'भाषा चुनें',
    user_access: 'उपयोगकर्ता लॉगिन / पंजीकरण',
    admin_access: 'व्यवस्थापक',
    volunteer_access: 'स्वयंसेवक लॉगिन / पंजीकरण',
    anonymous_report: 'गुमनाम रूप से रिपोर्ट करें',
    login: 'लॉग इन करें',
    register: 'पंजीकरण करें',
    report_issue: 'समस्या की रिपोर्ट करें',
    my_reports: 'मेरी रिपोर्ट',
    emergency_call: 'आपातकालीन कॉल',
    instructions: 'निर्देश / सहायता',
    name: 'नाम',
    phone: 'फ़ोन नंबर',
    age: 'आयु',
    city: 'शहर',
    email: 'ईमेल',
    password: 'पासवर्ड',
    confirm_password: 'पासवर्ड की पुष्टि करें',
    submit: 'जमा करें',
    back: 'वापस',
    assistant_title: 'हेल्पहब सहायक',
    assistant_subtitle: 'सामान्य समस्याओं में सहायता पाने के लिए हमारे AI बॉट के साथ चैट करें।',
    assistant_greeting: "नमस्ते! मैं हेल्पहब का स्वचालित सहायक हूँ। आप मुझसे 'मैं छवि अपलोड नहीं कर पा रहा हूँ', 'स्थान काम नहीं कर रहा है', या 'समस्या की रिपोर्ट कैसे करें' जैसे प्रश्न पूछ सकते हैं। आज मैं आपकी क्या सहायता कर सकता हूँ?",
    chat_placeholder: 'अपना प्रश्न यहाँ टाइप करें...',
    search_location: '📍 स्थान खोजें',
    search_placeholder: 'शहर या क्षेत्र टाइप करें (जैसे तिरुपति, आंध्र प्रदेश)',
    search_button: 'खोजें',
    searching: 'खोज रहे हैं...',
    search_help_text: 'रिपोर्ट जमा करने से पहले मानचित्र देखने और अपने स्थान की पुष्टि करने के लिए कृपया स्थान खोजें।',
    confirmed: '📍 पुष्टि की गई',
    re_enter_location: '✏️ स्थान फिर से दर्ज करें',
    confirm_location_button: '✅ इस स्थान की पुष्टि करें',
    category: '🏷️ श्रेणी',
    category_placeholder: 'जैसे पशु मुद्दा, सड़क, कचरा...',
    upload_photo: '📸 फोटो अपलोड करें',
    voice_input: '🎤 वॉयस इनपुट',
    start_recording: 'रिकॉर्डिंग शुरू करें',
    stop_recording: 'रिकॉर्डिंग बंद करें',
    recording_status: 'रिकॉर्डिंग हो रही है...',
    manual_input: '⌨️ मैनुअल टेक्स्ट इनपुट',
    manual_input_placeholder: 'समस्या का विस्तार से वर्णन करें...',
    contact_info_label: 'संपर्क जानकारी छोड़ें (वैकल्पिक)',
    contact_info_help: 'यदि आस-पास कोई स्वयंसेवक नहीं है, तो व्यवस्थापक इस मुद्दे के संबंध में आपसे संपर्क कर सकता है।',
    contact_info_placeholder: 'ईमेल या फ़ोन नंबर',
    user_dashboard: 'उपयोगकर्ता डैशबोर्ड',
    account_id: 'खाता आईडी',
    saving: 'सहेज रहा है...',
    confirmed_coords: 'निर्देशांक',
    smart_suggestions: '✨ स्मार्ट सुझाव (चुनने के लिए क्लिक करें)',
    selected_issue: 'चयनित मुद्दा',
    converted_text: 'परिवर्तित पाठ',
    strict_location_warning: 'रिपोर्ट जमा करने से पहले कृपया ऊपर अपना स्थान स्पष्ट रूप से पुष्टि करें।',
    logout: 'लॉगआउट',
    my_profile: 'मेरी प्रोफाइल',
  }
};

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('helphub_lang') as Language;
    if (saved && translations[saved]) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    localStorage.setItem('helphub_lang', lang);
    setLanguageState(lang);
  };

  const t = (key: string) => {
    return translations[language as Language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
