# Generated by Django 6.0.3 on 2026-03-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_report_admin_message_report_contact_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='resolved_proof',
            field=models.FileField(blank=True, null=True, upload_to='resolutions/'),
        ),
    ]
