# Generated by Django 6.0.3 on 2026-03-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_report_resolved_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='contact_request_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='contact_shared',
            field=models.BooleanField(default=False),
        ),
    ]
