# Generated by Django 6.0.3 on 2026-03-21 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_report_contact_request_reason_report_contact_shared'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_requests', to='core.report')),
                ('volunteer', models.ForeignKey(limit_choices_to={'role': 'VOLUNTEER'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('report', 'volunteer')},
            },
        ),
    ]
