# Generated by Django 5.0.3 on 2026-04-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_report_original_audio_alter_report_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
